"""Added Submission models

Revision ID: 1e14fe41ae59
Revises: df082549c2a1
Create Date: 2026-09-30 11:55:00.956227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e14fe41ae59'
down_revision: Union[str, Sequence[str], None] = 'df082549c2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('source_code', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPILING', 'RUNNING', 'DONE', name='submission_status_enum'), nullable=False),
    sa.Column('verdict', sa.Enum('AC', 'WA', 'TL', 'ML', 'RE', 'CE', 'JE', name='submission_verdict_enum'), nullable=True),
    sa.Column('failed_test', sa.Integer(), nullable=True),
    sa.Column('current_test', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('judged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_index('ix_submissions_status_id', 'submissions', ['status', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_submissions_status_id', table_name='submissions')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_table('submissions')
    # ### end Alembic commands ###
