"""add handle_lower to users

Revision ID: 685e7ce99b62
Revises: 6313ef2c9ede
Create Date: 2026-09-29 18:47:53.044046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685e7ce99b62'
down_revision: Union[str, Sequence[str], None] = '6313ef2c9ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('handle_lower', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_users_handle'), table_name='users')
    op.create_index(op.f('ix_users_handle_lower'), 'users', ['handle_lower'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_handle_lower'), table_name='users')
    op.create_index(op.f('ix_users_handle'), 'users', ['handle'], unique=True)
    op.drop_column('users', 'handle_lower')
    # ### end Alembic commands ###
